name: Build
on:
    push:
    pull_request:
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            # clone the repo
            - uses: actions/checkout@v3

            - name: install Nodejs
              uses: actions/setup-node@v3
              with:
                  node-version: '22'

            - name: install pnpm
              uses: pnpm/action-setup@v2
              with:
                  version: 8

            - name: install dependencies
              run: pnpm install

            - name: check prettier
              run: pnpm prettier-check
